/** Production UI copy — Japanese, user-facing only */
export const copy = {
  app: {
    name: "Cowell OCR",
    tagline: "現地調査 → スプレッドシート",
    description:
      "手書きのLED調査シートをOCRで読み取り、Googleスプレッドシートへ登録します。",
  },
  nav: {
    menu: "メニュー",
    home: "ホーム",
    newSurvey: "新規調査",
    newShort: "新規",
    account: "アカウント",
  },
  login: {
    title: "ログイン",
    subtitle: "管理者アカウントでサインイン",
    email: "メールアドレス",
    password: "パスワード",
    submit: "サインイン",
    submitting: "ログイン中…",
    loggedOut: "ログアウトしました。再度サインインしてください。",
    heroEyebrow: "LED現地調査",
    heroTitle: "現地調査を、\nデジタルに。",
    heroBody:
      "手書きのLED調査シートをOCRで読み取り、Googleスプレッドシートへ。調査記録のデジタル化と、発注業務の効率化を支援します。",
    footer: "Cowell · 現地調査デジタル化",
  },
  dashboard: {
    eyebrow: "ホーム",
    greeting: (name: string) => `${name}さん`,
    title: "現地調査を、光の速さで記録",
    body: "調査シートをアップロードし、OCRで読み取った結果を確認・編集して、スプレッドシートに登録できます。",
    cta: "新規調査を開始",
    workflowEyebrow: "作業の流れ",
    workflowTitle: "調査から登録まで",
    steps: [
      { label: "アップロード", desc: "画像・PDFを選択" },
      { label: "読み取り", desc: "AIが表を解析" },
      { label: "確認", desc: "内容を編集" },
      { label: "登録", desc: "スプレッドシートへ" },
    ],
    specs: [
      { label: "対応形式", value: "PDF · 画像" },
      { label: "読み取り", value: "AI OCR" },
      { label: "出力先", value: "Google スプレッドシート" },
    ],
  },
  survey: {
    back: "ホームに戻る",
    title: "新規調査",
    subtitle: "現地調査シートをアップロードし、読み取り結果を登録します",
    files: "調査ファイル",
    prompt: "読み取り指示",
    promptHint: "表の形式や出力ルールを指定できます。通常は既定のままで問題ありません。",
    runOcr: "読み取りを開始",
    processing: "読み取り中…",
    processingFiles: (n: number) => `${n}件のファイルを処理しています`,
    reviewTitle: "読み取り結果",
    reviewRows: (n: number) => `${n}件`,
    tabTable: "表",
    tabRaw: "原文",
    export: "スプレッドシートに登録",
    exporting: "登録中…",
    exportProgress: "スプレッドシートに書き込み中…",
    completeTitle: "登録が完了しました",
    completeBody: (n: number) => `${n}件のデータをスプレッドシートに登録しました`,
    openSheet: "スプレッドシートを開く",
    newSurvey: "続けて調査する",
    usage: {
      duration: "処理時間",
      tokens: "トークン",
      cost: "概算費用",
    },
  },
  upload: {
    drop: "ファイルを選択またはドラッグ",
    dropActive: "ドロップしてアップロード",
    formats: "PNG · JPEG · WEBP · PDF — 最大 20MB · 複数選択可",
    quality: "画質設定",
  },
  table: {
    empty: "読み取り結果がありません",
    footer: (n: number) => `${n}件 — セルをクリックして編集`,
  },
  auth: {
    logout: "ログアウト",
  },
  errors: {
    ocrFailed: "読み取りに失敗しました",
    exportFailed: "スプレッドシートへの登録に失敗しました",
    loginFailed: "ログインに失敗しました",
  },
} as const;
