/** Production UI copy — Japanese, user-facing only */
export const copy = {
  app: {
    name: "Cowell OCR",
    tagline: "現地調査 → スプレッドシート",
    description:
      "手書きのLED調査シートをOCRで読み取り、Googleスプレッドシートへ登録します。",
  },
  nav: {
    menu: "メニュー",
    home: "ホーム",
    newSurvey: "新規調査",
    newShort: "新規",
    account: "アカウント",
  },
  login: {
    title: "ログイン",
    subtitle: "管理者アカウントでサインイン",
    email: "メールアドレス",
    password: "パスワード",
    submit: "サインイン",
    submitting: "ログイン中…",
    loggedOut: "ログアウトしました。再度サインインしてください。",
    newPassword: "新しいパスワード",
    newPasswordSubtitle: "初回ログインです。新しいパスワードを設定してください。",
    newPasswordHint: "8文字以上で設定してください",
    newPasswordSubmit: "パスワードを設定して続行",
    heroEyebrow: "LED現地調査",
    heroTitle: "現地調査を、\nデジタルに。",
    heroBody:
      "手書きのLED調査シートをOCRで読み取り、Googleスプレッドシートへ。調査記録のデジタル化と、発注業務の効率化を支援します。",
    footer: "Cowell · 現地調査デジタル化",
  },
  dashboard: {
    eyebrow: "ダッシュボード",
    greetingTitle: "お疲れさまです",
    greetingUser: (name: string) => `${name}さん`,
    title: "現地調査資料を、「AI」で自動転記",
    titleBefore: "現地調査資料を、「",
    titleHighlight: "AI",
    titleAfter: "」で自動転記",
    body: "現地調査資料（手書き）をアップロードし、「AI」が内容を読み取り、スプレッドシートへ自動転記できます。",
    cta: "新規調査を開始",
    workflowEyebrow: "ワークフロー",
    workflowTitle: "現地調査資料（手書き）から自動転記まで",
    statusOnline: "システム稼働中",
    steps: [
      { label: "資料アップロード", desc: "画像・PDFを選択" },
      { label: "読み取り", desc: "「AI」が内容を抽出" },
      { label: "結果確認", desc: "内容を確認・編集" },
      { label: "自動転記", desc: "スプレッドシートへ" },
    ],
    capabilities: [
      {
        title: "マルチフォーマット",
        desc: "PNG · JPEG · WEBP · PDF に対応。現場で撮影した画像をそのままアップロード。",
      },
      {
        title: "「AI」にて自動読み込み",
        desc: "手書き・印刷混在の調査シートから、表形式データを高精度で抽出。",
      },
      {
        title: "スプレッドシート連携",
        desc: "確認後、ワンクリックでGoogleスプレッドシートに自動転記。",
      },
    ],
    specs: [
      { label: "対応形式", value: "PDF · 画像" },
      { label: "読み取りエンジン", value: "Gemini AI" },
      { label: "出力先", value: "Google スプレッドシート" },
    ],
  },
  survey: {
    back: "ホームに戻る",
    title: "新規調査",
    subtitle: "現地調査シートをアップロードし、読み取り結果を登録します",
    files: "調査ファイル",
    prompt: "読み取り指示",
    promptHint: "表の形式や出力ルールを指定できます。通常は既定のままで問題ありません。",
    runOcr: "読み取りを開始",
    processing: "読み取り中…",
    processingFiles: (n: number) => `${n}件のファイルを処理しています`,
    processingHint: "大きなPDFは1〜2分かかることがあります。この画面を閉じないでください。",
    processingPhase: {
      preparing: "準備しています…",
      uploading: "ファイルを送信しています…",
      reading: "AIが表データを読み取っています…",
      finishing: "結果を整理しています…",
      preparingShort: "準備",
      uploadingShort: "送信",
      readingShort: "読み取り",
      finishingShort: "完了",
    },
    reviewTitle: "読み取り結果",
    reviewRows: (n: number) => `${n}件`,
    tabTable: "表",
    tabRaw: "RAW",
    rawHint: "画像内の表をTSV形式で出力します。",
    export: "スプレッドシートに登録",
    exportCsv: "CSVでエクスポート",
    connectGoogle: "Googleに接続して登録",
    exporting: "登録中…",
    exportingTitle: "Google Driveへ登録中",
    exportProgress: "スプレッドシートに書き込み中…",
    exportProgressHint: "完了するまでこの画面を閉じないでください。",
    exportWaitingAuth: "アカウント選択待ち",
    exportAuthHint: "表示されたGoogleのウィンドウでアカウントを選択してください。",
    connectingGoogle: "Googleに接続",
    exportPhase: {
      connecting: "Googleアカウントを確認しています…",
      folders: "フォルダを準備しています…",
      spreadsheet: "スプレッドシートに書き込んでいます…",
      photos: "写真をアップロードしています…",
      sources: "元ファイルをアップロードしています…",
      finishing: "登録を完了しています…",
      connectingShort: "接続",
      foldersShort: "フォルダ",
      spreadsheetShort: "シート",
      photosShort: "写真",
      sourcesShort: "元ファイル",
      finishingShort: "完了",
    },
    completeTitle: "登録が完了しました",
    completeBody: (n: number) => `${n}件のデータをスプレッドシートに登録しました`,
    completeBodyCsv: (n: number) => `${n}件のデータをCSVファイルとして保存しました`,
    openSheet: "案件フォルダーを開く",
    downloadCsv: "CSVを再ダウンロード",
    newSurvey: "続けて新規調査を開始する",
    projectName: "案件名（フォルダー名）",
    projectNameHint: "案件フォルダーを入力してください",
    projectNamePlaceholder: "例: 学校法人郁文館夢学園",
    projectNameDuplicate: "この案件名は既に存在します。別の名前を入力してください",
    projectNameChecking: "案件名を確認中…",
    projectNameAvailable: "この案件名は利用できます",
    projectNameRequired: "案件名を入力してください",
    rootFolder: "ルートフォルダ",
    rootFolderHint: "My Drive直下",
    rootFolderPlaceholder: "選択してください",
    rootFolderRequired: "ルートフォルダを選択してください",
    rootFolderLast: "前回",
    rootFolderEmpty: "候補がありません",
    driveAccount: "Googleアカウント",
    driveAccountNone: "未接続",
    driveAccountConnect: "Googleに接続",
    driveAccountSwitch: "切替",
    driveAccountRequired: "Googleに接続してからフォルダを選択してください",
    destinationTitle: "Googleドライブの保存設定",
    destinationHint: "保存先:",
    destinationInvalid: "ルートフォルダと一意の案件名を入力してください",
    usage: {
      duration: "処理時間",
      tokens: "トークン",
      cost: "コスト",
    },
  },
  upload: {
    drop: "ファイルを選択またはドラッグ",
    dropActive: "ドロップしてアップロード",
    formats: "画像（任意の形式）· PDF — 最大 20MB · 複数選択可",
    quality: "画質設定",
  },
  table: {
    empty: "読み取り結果がありません",
    footer: (n: number) => `${n}件 — セルをクリックして編集`,
    searchPlaceholder: "フロア・場所・品番などで検索…",
    pageSize: "表示件数",
    noMatches: "該当する行がありません",
    range: (from: number, to: number, total: number) =>
      total === 0 ? "0件" : `${from}–${to} / ${total}件`,
    filteredOf: (total: number) => `全${total}件から絞り込み`,
    prev: "前へ",
    next: "次へ",
    photo: "写真",
    attachPhoto: "写真を添付",
    changePhoto: "変更",
    removePhoto: "削除",
    photoAttached: "添付済み",
    close: "閉じる",
    photoPreview: "写真プレビュー",
    deleteRow: "行を削除",
    deleteRowTitle: "この行を削除しますか？",
    deleteRowBody:
      "この調査データ行を一覧から削除します。削除後は元に戻せません。",
    deleteRowTarget: "削除対象",
    deleteRowConfirm: "削除する",
    deleteRowCancel: "キャンセル",
    rowFallback: (n: number) => `${n}行目`,
  },
  auth: {
    logout: "ログアウト",
  },
  errors: {
    ocrFailed: "読み取りに失敗しました。ファイルを確認のうえ、再度お試しください。",
    exportFailed: "スプレッドシートへの登録に失敗しました",
    loginFailed: "ログインに失敗しました",
    serviceNotConfigured: "現在、読み取り機能をご利用いただけません。管理者にお問い合わせください。",
    serviceUnavailable: "サービスに接続できませんでした。しばらくしてから再度お試しください。",
    ocrBusy:
      "読み取りサービスが混み合っています。しばらくしてから再度お試しください。",
  },
} as const;
